name: taxcalc-dev
channels:
  - conda-forge
dependencies:
- "python>=3.9, <3.13"
- "numpy>=1.26,<1.27"
- "pandas>=2.2"
- "bokeh>=2.4"
- "marshmallow<3.22"    # to work around paramtools bug
- "paramtools>=0.18.2"  # requires marshmallow>=3.0
- numba
- curl
- pytest
- pytest-xdist
- pycodestyle
- pylint
- coverage
- behresp
- openpyxl
- pip
- pip:
    - jupyter-book
